<a href="https://colab.research.google.com/github/remjw/apple/blob/main/_graduate-python-questions_key.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
punc = '''
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
'''
# import string
# string.punctuation

In [ ]:
import numpy as np
punc = '''
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
'''

def word_frequency(text):
    word_cnt = dict()
    text = "".join([c for c in text.lower() if c not in punc])
    words = text.split()
    for word in words:
        if word in word_cnt:
            word_cnt[word] += 1
        else:
            word_cnt[word] = 1
    return word_cnt

def decrypt(text, code={'A': '%', 'a': '9', 'B': '@', 'b': '#'}):
    decrypted = ""
    for ch in text:
        for k, v in code.items():
            if v == ch:
                decrypted += k
                break
        else:
            decrypted += "-"
    return decrypted

def count_nonnegative_numbers(arr):
    count = 0
    print(arr)
    for row in arr:
        for num in row:
            if num >= 0:
                count += 1
    return count

if __name__ == "__main__":
    test_string = '''Overall, NumPy arrays are typically more appropriate for
    numerical computations and scientific computing, while Python lists are more
    flexible and versatile for general-purpose programming.
    '''
    print(word_frequency(test_string))
    
    test_text = "%%#9---@"
    print(decrypt(test_text))

    test_array = np.random.randint(-99, 100, size=(10, 10))
    print(count_nonnegative_numbers(test_array))

## All in one line?

In [ ]:
def word_frequency(text, punc="!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"):
  return { 
      word : text.lower().count(word) 
      for word in set( "".join([c for c in text.lower() if c not in punc]).split() )
      }

test_string = '''Overall, NumPy Arrays are NumPy arrays are ...!'''
for k, v in word_frequency(test_string).items():
  print(f'{k} : {v}')

arrays : 2
are : 2
numpy : 2
overall : 1


In [ ]:
def decrypt(text, code={'A': '%', 'a': '9', 'B': '@', 'b': '#'}):
  decode = dict(zip(code.values(), code.keys()))
  return "".join([decode[c] if c in decode else "-" for c in text])

print(decrypt("%%#9---@"))

AAba---B


In [ ]:
def count_nonnegative_numbers(arr):
  return len([ 1 for row in arr for cell in row if cell >= 0 ])

dim = 3
test_array = np.random.randint(-99, 100, size=(dim, dim))
print(test_array)
print(count_nonnegative_numbers(test_array))

[[  7  90  22]
 [ 95 -21  17]
 [ 61 -81 -18]]
6


### Numpy Broadcasting

In [ ]:
import numpy as np
X = np.array([list(range(5)),  list(range(-5,0))])
print(X)
print(X * 2)

In [ ]:
X = [list(range(5)), list(range(-5, 0))]
print(X)

double = []
for r in X:
    row = []
    for value in r:
        value *= 2
        row.append(value)
    double.append(row)

print(double)

[[0, 1, 2, 3, 4], [-5, -4, -3, -2, -1]]
[[0, 2, 4, 6, 8], [-10, -8, -6, -4, -2]]


### Mapping letters to digits

In [ ]:
mapping = {'A': '2', 'B': '2', 'C': '2','D': '3', 'E': '3', 'F': '3','G': '4', 'H': '4', 'I': '4',
                    'J': '5', 'K': '5', 'L': '5','M': '6', 'N': '6', 'O': '6','P': '7', 'Q': '7', 'R': '7', 
                    'S': '7','T': '8', 'U': '8', 'V': '8', 'W': '9', 'X': '9', 'Y': '9', 'Z': '9'
}
phone = "555-GET-FOOD" # input("Enter a phone number to be translated: ")
translated = "".join([ mapping[c.upper()] if c.isalpha() else c for c in phone ])
print(translated)

555-438-3663
