<a href="https://colab.research.google.com/github/remjw/apple/blob/main/_graduate-python-questions_key.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
punc = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"

In [19]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
import numpy as np
punc = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
# string.punctuation

def word_frequency(text):
    word_cnt = dict()
    text = "".join([c for c in text.lower() if c not in punc])
    words = text.split()
    for word in words:
        if word in word_cnt:
            word_cnt[word] += 1
        else:
            word_cnt[word] = 1
    return word_cnt

def decrypt(text, code={'A': '%', 'a': '9', 'B': '@', 'b': '#'}):
    decrypted = ""
    for ch in text:
        for k, v in code.items():
            if v == ch:
                decrypted += k
                break
        else:
            decrypted += "-"
    return decrypted

def count_nonnegative_numbers(arr):
    count = 0
    print(arr)
    for row in arr:
        for num in row:
            if num >= 0:
                count += 1
    return count

if __name__ == "__main__":
    test_string = '''Overall, NumPy arrays are typically more appropriate for
    numerical computations and scientific computing, while Python lists are more
    flexible and versatile for general-purpose programming.
    '''
    print(word_frequency(test_string))
    
    test_text = "%%#9---@"
    print(decrypt(test_text))

    test_array = np.random.randint(-99, 100, size=(10, 10))
    print(count_nonnegative_numbers(test_array))

## All in one line?

In [26]:
def word_frequency(text, punc="!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"):
  return { 
      word : text.lower().count(word) 
      for word in set( "".join([c for c in text.lower() if c not in punc]).split() )
      }

test_string = '''Overall, NumPy Arrays are NumPy arrays are ...!'''
for k, v in word_frequency(test_string).items():
  print(f'{k} : {v}')

arrays : 2
are : 2
numpy : 2
overall : 1


In [43]:
def decrypt(text, code={'A': '%', 'a': '9', 'B': '@', 'b': '#'}):
  decode = dict(zip(code.values(), code.keys()))
  return "".join([decode[c] if c in decode else "-" for c in text])

print(decrypt("%%#9---@"))

AAba---B


In [51]:
def count_nonnegative_numbers(arr):
  return len([ 1 for row in arr for cell in row if cell >= 0 ])

dim = 3
test_array = np.random.randint(-99, 100, size=(dim, dim))
print(test_array)
print(count_nonnegative_numbers(test_array))

[[  7  90  22]
 [ 95 -21  17]
 [ 61 -81 -18]]
6
